language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

before_install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libgmock-dev