language: cpp

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

before_install:
  - sudo apt-get install libgtest-dev
  - sudo apt-get install google-mock
  - sudo ./build_gtest.sh
